---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150001'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-LDAPapi
no_index:
  directory:
    - t
    - inc
requires:
  Convert::ASN1: '0.19'
resources:
  repository: https://github.com/quanah/net-ldapapi.git
version: v3.0.5
